name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Step 1: Get your code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Build your project
      - name: Build project
        run: npm run build

      # Step 5: Deploy to GitHub Pages (with history)
      - name: Deploy to GitHub Pages
        run: |
          # Configure git identity
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Save the build output
          mkdir -p /tmp/dist
          cp -r dist/* /tmp/dist/

          #cname
          echo 'nihesh.codes' > /tmp/dist/CNAME

          # Check if gh-pages branch exists
          if git ls-remote --heads origin gh-pages | grep -q 'gh-pages'; then
            # Branch exists - fetch and check it out
            git fetch origin gh-pages
            git checkout gh-pages
          else
            # First time - create the branch
            git checkout --orphan gh-pages
            git reset --hard
            git commit --allow-empty -m "Initial gh-pages branch"
            git push origin gh-pages
            git checkout gh-pages
          fi

          # Clean the working directory (but keep .git folder)
          find . -maxdepth 1 ! -name .git ! -name . -exec rm -rf {} \;

          # Copy build files to root (from saved location)
          cp -r /tmp/dist/* .

          # Add all files
          git add .

          # Commit with timestamp
          git commit -m "Deploy to GitHub Pages - $(date +'%Y-%m-%d %H:%M:%S')"

          # Push to gh-pages branch (no force)
          git push origin gh-pages
